### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by nickeubank** [Ofosu-Osei/seaborn_objects_recipes#13]
- [ ] Add citations where we've borrowed code to the README (e.g. the starter code for lowess came from that issue). Error on the side of giving too much credit to other people — always safer than having people mad at you.
- [ ] Post about the library over on the seaborn repo under the Discussion tab saying we made this, citing the people from whom we've borrowed code (with an `@`), and asking for feedback, especially around (a) having this as a separate library (as opposed to rolling into seaborn.objects directly), and (b) how we're handling confidence intervals. I'm happy to write and post that if you want, but I think it should probably be you to get you full credit!

**Comment by Ofosu-Osei** [comment]
I'll work on that as soon as possible.
Thanks,
Ofosu
________________________________
From: Nick Eubank ***@***.***>
Sent: Thursday, July 11, 2024 2:32 PM
To: Ofosu-Osei/seaborn_objects_recipes ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Ofosu-Osei/seaborn_objects_recipes] Next steps (Issue #13)


  *    Add citations where we've borrowed code to the README (e.g. the starter code for lowess came from that issue). Error on the side of giving too much credit to other people — always safer than having people mad at you.
  *    Post about the library over on the seaborn repo under the Discussion tab saying we made this, citing the people from whom we've borrowed code (with an @), and asking for feedback, especially around (a) having this as a separate library (as opposed to rolling into seaborn.objects directly), and (b) how we're handling confidence intervals. I'm happy to write and post that if you want, but I think it should probably be you to get you full credit!
